#.pages.yml
media:
  input: public/uploads/media # Where PagesCMS saves uploaded files in the repo
  output: /uploads/media    # How the SSG should reference these files

content:
  - name: student_profiles
    label: Student Profiles
    path: src/content/students # Directory where student profile Markdown files will be stored
    type: collection
    fields:
      - { name: studentName, label: Full Name, type: string, required: true }
      - { name: profileImage, label: Profile Picture, type: image, media_folder: 'student_photos' } # Optional: subfolder within media path
      - { name: graduationYearExpected, label: Expected Graduation Year (University), type: string }
      - { name: currentGradeLevel, label: Current Grade Level, type: string }
      - { name: majorOrFieldOfStudy, label: Major / Field of Study, type: string }
      - { name: schoolName, label: School / University Name, type: string }
      - { name: bioOrAspirations, label: Biography / Aspirations, type: rich-text }
      - { name: hobbiesAndInterests, label: Hobbies & Interests, type: text }
      - { name: favoriteQuote, label: Favorite Quote, type: text }
      - { name: thankYouMessage, label: Message of Thanks, type: rich-text }
      - { name: programStartDate, label: Date Joined Program, type: date }
      # Add other fields from Table 1 as needed
    filename: '{year}-{month}-{day}-{slugify(studentName)}.md' # Generates filenames like "2024-05-15-maria-jose-garcia.md"
                                                              # {slugify(studentName)} creates a URL-friendly version of the name.
                                                              # Consider using a unique ID if names might not be unique.
    view: # Optional: Customize how profiles are listed within the PagesCMS interface
      fields: [studentName, graduationYearExpected, currentGradeLevel] # Fields visible in the list view
      primary: studentName # Field used as the main identifier in the list
      sort:
        - field: studentName
          order: asc # Default sort order